//==============================================================================
// TANG NANO 20K TIMING CONSTRAINTS - HDMI KALEIDOSCOPIC PATTERN GENERATOR
//==============================================================================
// This SDC (Synopsys Design Constraints) file defines timing requirements for
// the FPGA design. Proper timing constraints are essential for stable operation
// at high frequencies, especially for HDMI video generation.
//
// SYSTEM CLOCK SPECIFICATION:
// ===========================
// Input Clock: 27MHz crystal oscillator on Tang Nano 20K
// Period: 37.04ns (1/27MHz = 37.037ns, rounded for timing margin)
// This clock drives the PLL which generates the high-speed TMDS clocks needed
// for 1280x720@60Hz HDMI output (371.25MHz TMDS, 74.25MHz pixel clock).
//
// TIMING ANALYSIS:
// ================
// The design uses internal clock domains generated by PLL:
// - 371.25MHz TMDS serialization clock (for HDMI transmission)  
// - 74.25MHz pixel clock (for video timing and pattern generation)
// The 27MHz input constraint allows the tools to properly analyze timing
// across all generated clock domains for maximum performance.
//==============================================================================

// ---- PRIMARY SYSTEM CLOCK CONSTRAINT ----
// Constrains the 27MHz input clock with adequate timing margin
create_clock -name I_clk -period 37.04  [get_ports {I_clk}] -add